# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - ./mongo:/data/db

  # mongo-express:
  #  image: mongo-express
  #  restart: unless-stopped
  #  ports:
  #    - 8081:8081
  #  environment:
  #    ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #    ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #    ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server /etc/redis.conf
    # ports:
    #   - 6379:6379
    volumes:
      - ./redis:/data
      - ./config/redis.conf:/etc/redis.conf

  livekit:
    image: livekit/livekit-server:v1.3
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    # network_mode: "host"
    ports:
      - "7881:7881/tcp"
      - "50000-60000:50000-60000/udp"
      - "5349:5349/tcp"
      - "3478:3478/udp"
    depends_on:
      - redis
    volumes:
      - ./config/livekit.yaml:/etc/livekit.yaml

  audon:
    build: .
    image: namekuji/audon
    env_file:
      - .env.production
    restart: unless-stopped
    ports:
      - "8100:8100"
    depends_on:
      - db
      - redis
      - livekit

  # redisinsight:
  #  image: redislabs/redisinsight:latest
  #  restart: unless-stopped
  #  ports:
  #    - 8001:8001
  #  volumes:
  #    - redisinsight:/db
