version: '3.1'

services:
  devcontainer:
    image: "mcr.microsoft.com/devcontainers/universal:2-linux"
    volumes:
      - ../..:/workspaces:cached
    networks:
      - internal_network
      - external_network
    command: sleep infinity

  db:
    image: mongo:6
    restart: unless-stopped
    networks:
      - internal_network
    # ports:
    #   - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    networks:
      - internal_network
      - external_network
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@db:27017/

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server
    networks:
      - internal_network
    # ports:
    #   - "6379:6379"

  redisinsight:
    image: redislabs/redisinsight:latest
    restart: unless-stopped
    networks:
      - internal_network
      - external_network
    ports:
      - 8082:8001

  livekit:
    image: livekit/livekit-server:v1.3
    command: --dev --bind 0.0.0.0
    restart: unless-stopped
    ports:
      - "7881:7881"
      - "7882:7882/udp"
    networks:
      - internal_network
      - external_network

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - internal_network
      - external_network
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./certs:/etc/caddy/certs:ro

networks:
  external_network:
  internal_network:
    internal: true
