version: '3.1'

services:
  devcontainer:
    image: "mcr.microsoft.com/devcontainers/base:jammy"
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  db:
    image: mongo:6
    restart: unless-stopped
    # ports:
    #   - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@db:27017/

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server
    # ports:
    #   - "6379:6379"

  redisinsight:
    image: redislabs/redisinsight:latest
    restart: unless-stopped
    ports:
      - 8082:8001

  livekit:
    image: livekit/livekit-server:v1.3
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    ports:
      - "7881:7881"
      - "7882:7882/udp"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml:ro

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./certs:/etc/caddy/certs:ro
